---
version: '3'
volumes:
  share:
services:
  server:
    build: .
    image: index.docker.io/oaklabs/app-demo-menu:latest
    devices:
      - /dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      - ./src:/app/src
      - share:/data/share
    environment:
      - NODE_ENV=development